### ISSUE TITLE
Terminal Notifier

### ISSUE THREAD

**Issue by djekl** [LasseHaslev/executor#1]
Hey @LasseHaslev, massive thanks for this, found it from [this thread over on Laracasts](https://laracasts.com/discuss/channels/testing/laravel-mix-and-phpunit).

Any chance you can get this to work with `terminal-notifier` like the old `gulp tdd` command did?

**Comment by LasseHaslev** [comment]
Hi @djekl and sorry for delayed answer.

I am glad you liked the package, but I don't think this package should be handling `terminal-notifier` cause of this package main purpose is not to work as a `tdd`-only, but to watch for any file changes and execute any command the user want.

Personally i achieved the same result as you asking for on OSX through  ```iTerm2 triggers```:
```Preferences > Profiles > Advanced > Triggers```

One regular expression for ```OK (.+)$``` with a action of ```Run Command...``` and a parameter of ```osascript -e 'display notification "Test successful!" with title "Green!"'``` and the same approach for ```ERROR``` and ```FAILURES!```.
